# Dependencies for low_dimensional_learning
# USAGE (from working directory):
# conda env create -f environment.yaml
# conda activate rnn_sandbox
# pip install -e .
name: rnn_sandbox

channels:
  - rdkit
  - defaults
  - conda-forge
dependencies:
  - pip=20.3.1
  - pyyaml=5.3.1
  - scipy=1.4.1
  - scikit-learn=0.23.2
  - logzero=1.5.0
  - tini=0.18.0
  - matplotlib=3.3.1
  - numpy=1.18.5
  - cudatoolkit=11.0
  - cudnn=8.0
  - uuid
  - pip:
    - tensorflow-gpu==2.5.0
    - tensorflow-probability==0.12.2
